# Generated by Django 5.0 on 2025-09-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_category_slug_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=123, upload_to='products/'),
            preserve_default=False,
        ),
    ]
